# Generated by Django 4.0.5 on 2022-06-27 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagrams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('xml', models.TextField()),
                ('properties', models.TextField()),
                ('creation_date', models.DateTimeField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('diagram_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stories', to='diagrams.diagrams')),
            ],
        ),
    ]
