# Generated by Django 4.0.5 on 2022-07-11 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('diagrams', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Diagrams',
            new_name='Diagram',
        ),
    ]
