# Generated by Django 4.0.5 on 2022-07-28 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagrams', '0003_diagram_update_date_alter_diagram_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagram',
            name='project_id',
        ),
    ]
