# Generated by Django 4.0.5 on 2022-07-29 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagrams', '0004_remove_diagram_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagram',
            name='properties',
            field=models.TextField(blank=True, null=True),
        ),
    ]
