# Generated by Django 4.0.5 on 2022-07-31 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagrams', '0007_alter_diagram_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagram',
            old_name='user',
            new_name='user_id',
        ),
    ]
