# Generated by Django 4.0.5 on 2022-09-10 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_description_project_user_id'),
        ('diagrams', '0009_diagram_json_user_histories_delete_userstory'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagram',
            name='id_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
