# Generated by Django 4.0.5 on 2022-09-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagrams', '0010_diagram_id_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagram',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='diagram',
            name='json_user_histories',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
