# Generated by Django 4.0.5 on 2022-09-19 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagrams', '0012_remove_diagram_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagram',
            name='properties',
            field=models.TextField(blank=True, null=True),
        ),
    ]
