# Generated by Django 4.0.5 on 2022-09-21 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagrams', '0014_alter_diagram_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagram',
            name='properties',
        ),
    ]
