# Generated by Django 4.0.5 on 2022-10-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_sentence', models.TextField()),
                ('second_sentence', models.TextField()),
            ],
        ),
    ]
