# Generated by Django 4.0.5 on 2022-10-01 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('association_rules', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='associationrules',
            options={'verbose_name': 'Association Rule', 'verbose_name_plural': 'Association Rules'},
        ),
    ]
