# Generated by Django 4.0.5 on 2022-10-01 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('association_rules', '0002_alter_associationrules_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssociationRules',
        ),
    ]
