export const API_URL = process.env.REACT_APP_API_HOST;
export const MICROSERVICE_CALCULATOR_URL = process.env.REACT_APP_MICROSERVICE_CALCULATOR_URL;
export const MICROSERVICE_VIEWER_URL = process.env.REACT_APP_MICROSERVICE_VIEWER_URL;